version: "3.3"

services:
  mongodb:
    image: mongo
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: "mongo"
      MONGO_INITDB_ROOT_USERNAME: "admin"
      MONGO_INITDB_ROOT_PASSWORD: "aFW#a4wgs4wq%Eh6dR7jT&K*YYG%$SF33Q=="
    volumes:
      # named volumes
      - "mongodb:/data/db"
      - "mongoconfig:/data/configdb"
      # Directory with init scripts
      - "./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro"

volumes:
  # default dir on ubuntu: /var/lib/docker/volumes
  mongodb:
  mongoconfig: